### ISSUE TITLE
ERC-165 and other standards enforcing gas limits

### ISSUE THREAD

**Issue by PhABC** [holiman/eip-1884-security#4]
I would be interested in knowing whether some contracts following ERC-165 would break with EIP-1884. ERC-165's `supportsInterface()` function is expected to cost less than 30k gas and it is possible that some contracts will throw if this limit is exceeded (I am not aware of the existence of such contracts nor have I looked for some). ERC-1155 uses a subset of ERC-165 and requires the call to `supportsInterface()` cost less than 10k gas.

Depending on the implementation, it is possible these functions are close to the limit and could exceed the limit proposed by their respective standards, which could be problematic.

**Comment by holiman** [comment]
Sorry, I thought I had already answered this, because it was discussed here: https://github.com/ethereum/EIPs/pull/2251

**Comment by holiman** [comment]
Short answer, as far as I can tell, no, they shouldn't break
